### PR TITLE
Add pvlib with pysam financial model tutorial

### PR DESCRIPTION
**Pull request by mjprilliman**
@brtietz can you test for functionality and review for content
@cpaulgilman and @janinefreeman can you review for content?
- I could add cashloan as well, but might not be able to cover it in the 15 minute time slot

### CODE REVIEW

**Review by cpaulgilman — COMMENTED** [review]
Please add:

* A requirements.txt file to facilitate using with virtual environments.
* A readme.md file with a brief description of what this example is about.

The SAM and pvlib logos are too big when I open the Jupyter Notebook file in Visual Studio Code:

image

**Comment by brtietz** [comment]
The example looks good on a quick read - I'll wait to run it until the requirements.txt file Paul requested is available. I agree with Paul's comments on the logo sizes.

Can you add some commented out code or a different cell to demonstrate ppa_soln_mode = 0 and setting an IRR target? I feel like calculating a PPA price is a powerful example that will garner some interest.

**Comment by mjprilliman** [comment]
Thanks for the review. I added the requirement and a simple readme.md. Also adjusted the image in the title and added commented code for the target irr mode.

**Comment by brtietz** [comment]
Thanks! The requirements.txt file fails with:

> ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\b\\abs_3cwz1w13nn\\croot\\aiobotocore_1701291550158\\work'

I expect the right move is to delete all of the lines that include file paths. See https://github.com/NREL/SAM/blob/patch/samples/Python%20Scripts/End%20Use%20Load%20Profiles/eulp/requirements.txt for an example.

**Comment by mjprilliman** [comment]
> Thanks! The requirements.txt file fails with:
> 
> > ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\b\abs_3cwz1w13nn\croot\aiobotocore_1701291550158\work'
> 
> I expect the right move is to delete all of the lines that include file paths. See https://github.com/NREL/SAM/blob/patch/samples/Python%20Scripts/End%20Use%20Load%20Profiles/eulp/requirements.txt for an example.

Just updated. I need to get more familiar with making the requirements.txt, I just looked up an automated process for it. Hopefully it works now.

**Comment by brtietz** [comment]
Unfortunately that didn't work either. Generally I try to be as minimal as possible with these - pip is pretty good at pulling in dependencies and too much in requirements.txt makes for an over-constrained problem. The notebook ran with the version that I pushed _after_ I added ipython ipykernel manually. I use those for VS Code, and am open to keeping it flexible for this example, but that's something worth noting in a README.

The notebook itself is close! Ending with the project cash flow graphic is great. I'd recommend adding:
1. A link to https://nrel-pysam.readthedocs.io/en/main/getting-started.html to explain what the JSON file does
2. Explicitly mention that system_use_lifetime_output = 0 means AC degradation. I'm ok to expand the example to DC degradation after the conference (and probably getting some advice from the pvlib team about how to do that in pvlib)
3. For any case like "financing" where there are more bullets than code, either add code to specify or delete the bullets.

**Review by brtietz — APPROVED** [review]
The latest looks good, thank you!

**Pull request merged**
